### ISSUE TITLE
You must configure the exact release and stemcell versions in broker.service_deployment

### ISSUE THREAD

**Issue by abhilash07** [pivotal-cf/on-demand-service-broker-release#18]
Hi i am trying to deploy kafka-example-service with on-demand-service-broker-release  (v0.20.0) and stemcell version (bosh-stemcell-3541.12-warden-boshlite-ubuntu-trusty-go_agent). But unexpectedly i am encountering below error.
<img width="1421" alt="screen shot 2018-04-13 at 9 37 44 am" src="https://user-images.githubusercontent.com/10971841/38711113-b1b45176-3efe-11e8-8b7a-75f43648d00b.png">

Any suggestions to overcome this error ???

Thanks in Advance.

**Comment by deniseyu** [comment]
Hi @abhilash07, there should be a top-level `stemcells` property in your broker manifest that looks like this:

```
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: '3468.21'
```

Can you confirm that you have this in your manifest, and that it's been uploaded to your director?

**Comment by abhilash07** [comment]
@deniseyu thanks for your quick responce, this is my yaml file.
[Kafka.txt](https://github.com/pivotal-cf/on-demand-service-broker-release/files/1940404/Kafka.txt)

Thanks in advance!!!

**Comment by deniseyu** [comment]
@abhilash07 did you close this because you resolved it on your own?

**Comment by abhilash07** [comment]
@deniseyu yes i solved this error
