### ISSUE TITLE
upgrade-all-service-instances will fail if BOSH doesn't allocate a worker within 30 seconds

### ISSUE THREAD

**Issue by abg** [pivotal-cf/on-demand-service-broker-release#20]
## Summary

When running the `upgrade-all-service-instances` errand, we are seeing repeated failures that look like this:

```
           [upgrade-all-service-instances] ... 5 errors occurred:  
             
           * Upgrade failed for service instance ${service_instance_guid}: Patch http://${broker}/mgmt/service_instances/${service_instance_guid}: http: ContentLength=51 with Body length 0  

```

These are random - not always the same service instance.  Investigating these failures, the upgrade actually succeeds but the upgrade-all-service-instances errand itself fails.

The common correlation between these failures is that the `PATCH` request from the errand to the broker to start this upgrade takes longer than 30 seconds for all failures

Here is an example of a PATCH Request that was reported as failed by the errand, but ultimately succeeded.  We see this took 51.3 seconds for the upgrade request to be accepted:

```
[on-demand-service-broker] ... Request PATCH /mgmt/service_instances/${GUID} b Completed 202 in 51.318329858s
```

This is a:
- [x] Bug report

## Steps to reproduce (if bug report)

This occurred in a multi-tenant bosh environment when we were running upgrades with a concurrency of 7.   We had been running with this configuration for some time, but perhaps the bosh director has been under higher load lately resulting in slower deployment times.

We suspect the 30 second timeout may come from the hardcoded setting here:

https://github.com/pivotal-cf/on-demand-service-broker/blob/1efb0c5bc590ecafd5743864cb1d581d296427e2/upgrader/upgrade_all_instances_errand_builder.go#L126

And suspect the error message (`http: ContentLength=51 with Body length 0`) is client side and the retry may be failing when the body initialized here is reused on the reattempt:

https://github.com/pivotal-cf/on-demand-service-broker/blob/1efb0c5bc590ecafd5743864cb1d581d296427e2/broker/services/services.go#L49

## How urgent is this?

- [X] We have a workaround, but would prefer to stop using it

We have vastly reduced the concurrency of upgrades to minimize when we hit timeouts, but these can still occur.  We would like to resolve this in the near future so we can continue to take advantage of faster upgrades.

**Comment by deniseyu** [comment]
Going to close this out, sounds like @crhino and @kirederik resolved the issue.
