### ISSUE TITLE
upgrade-all-service-instances errand has references to CF 

### ISSUE THREAD

**Issue by aclevername** [pivotal-cf/on-demand-service-broker-release#23]
## Summary

This is a:
- [ ] Feature request
- [x] Bug report
- [ ] Other issue

The `upgrade-all-service-instances` errand references `CF` despite the errand being run on a PKS deployment 

```
[upgrade-all-service-instances] 2018/08/30 10:16:58.742228 Upgrade progress summary: Sleep interval until next attempt: 1m0s; Number of successful upgrades so far: 0; Number of CF service instance orphans detected so far: 1; Number of deleted instances before upgrade could occur: 0; Number of operations in progress (to retry) so far: 0
```

Found here: https://github.com/pivotal-cf/on-demand-service-broker/blob/c1b919a4f6941c128af495b6d64a74e2b3fa2631/upgrader/logging_listener.go#L97

## Steps to reproduce (if bug report)

Run `upgrade-all-service-instances` errand on a PKS deployment and check log output

## How urgent is this?

- [ ] Our product or team is blocked until this is resolved
- [ ] We have a workaround, but would prefer to stop using it
- [x] This is a nice to have, but there is no immediate need for it

Paired with @mirahimage

**Comment by jacknewberry** [comment]
Fixed by https://github.com/pivotal-cf/on-demand-service-broker/commit/093e7b149d6658c33eadf6fec16e7b10710ab860.
