### ISSUE TITLE
doc for broker manifest

### ISSUE THREAD

**Issue by maplain** [pivotal-cf/on-demand-service-broker-release#26]
## Summary
This is a:
- [ ] Feature request
- [ ] Bug report
- [x] Other issue
        doc request

> Provide a brief summary of the bug or feature request. Please focus on the
problem statement rather than any potential solutions.

Couldn't find documentation on broker manifest: https://docs.pivotal.io/svc-sdk/odb/0-25/tile.html. Even though the object is defined here: https://github.com/pivotal-cf/on-demand-service-broker/blob/master/config/config.go#L23, developers should NOT dig into source code to figure out the meaning and implications of each field.

## What level of support do you need?

- [ ] We can PR this, following the [Contributing](contributing.md) guidelines
- [ ] We would like to cross-team pair with someone from the ODB SDK team
- [x] We don't know where to start with this

## How urgent is this?

- [ ] Our product or team is blocked until this is resolved
- [ ] We have a workaround, but would prefer to stop using it
- [x] This is a nice to have, but there is no immediate need for it

**Comment by FelisiaM** [comment]
Sounds fair.

We added a link to the broker spec in our docs. 

We'll be looking into ways of making it better in the future.

Thanks
