### ISSUE TITLE
DirectorJobRunner: - Deployment '' doesn't exist 

### ISSUE THREAD

**Issue by ktpv** [pivotal-cf/on-demand-service-broker-release#27]
## Summary

This is a:
- [X] Bug report

> Provide a brief summary of the bug or feature request. Please focus on the
problem statement rather than any potential solutions.

If service creation fails for whatever reason, i.e. Azure fails to create VMs, or config patterns or keys are incorrect, etc,  then the ODB service fails deployment.  When then trying to delete a broken deployment, the ODB service fails to delete the deployment.

This is the main error displayed
DirectorJobRunner: - Deployment '' doesn't exist 

## Use cases (if feature request)

> Please provide the use cases for this feature and detail the workflows this
would help with. If you have implemented a workaround for this already, please
explain how you are currently solving this problem.

cf purge-service and bosh delete-deployment are the workarounds.

Customers have 100s of instances and this workaround does not scale well.

## Steps to reproduce (if bug report)

> Please include SDK version, BOSH version and platform specifics. Please be
careful posting manifests here in case they contain secrets, but please keep
a copy of them in case we ask for them.

Any version of SDK or BOSH shows this issue.

## What level of support do you need?

- [X] We would like to cross-team pair with someone from the ODB SDK team

## How urgent is this?

- [X] Our product or team is blocked until this is resolved

Customers are impacted.

**Comment by winnab** [comment]
Hey @ktpv! 

Thanks for reaching out. We've tried a few things to reproduce this bug to get the `DirectorJobRunner: - Deployment '' doesn't exist` but, in both cases, we were able to successfully delete the service and deployment. 

What we've tried so far:
1. Configured a plan with an invalid VM type
1. Changed the start script for our service to exit 1

Can you give us more specifics for how we can recreate this bug ourselves? Once we see the issue, we can figure out what the next steps should be. We're happy to pair to find a fix.

Thanks
Winna and @kirederik

**Comment by ktpv** [comment]
Thank you for reviewing.  We're coordinating now with the partner to hold a live pairing session with you.

**Comment by winnab** [comment]
We had sessions with the partner where we advised converting their post-start script to a post-deploy errand. They have plans to implement this.
