### ISSUE TITLE
recreate-all-service-instances errand should support max in flight

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/on-demand-service-broker-release#54]
## Summary

In order to reduce the mean time of operation the recreate-all-service-instances should support max in flight similar to upgrade-all-services-instances.

This is a:
- [x] Feature request
- [ ] Bug report
- [ ] Other issue

## Use cases (if feature request)

Repaving is an operation that many operators leverage on tranditional bosh deployments and cloud foundry.  Having the ability to recreate all of the service instances without having to take a stemcell upgrade can improve the security posture of a foundation.  However, the time delta between upgrade-all-service-instances and recreate-all-service-instances is substantial given recreate all service instances is serial. 

## What level of support do you need?

- [ ] We can PR this, following the [Contributing](contributing.md) guidelines
- [ ] We would like to cross-team pair with someone from the ODB SDK team
- [x] We don't know where to start with this

## How urgent is this?

- [ ] Our product or team is blocked until this is resolved
- [ ] We have a workaround, but would prefer to stop using it
- [x] This is a nice to have, but there is no immediate need for it

**Comment by kirederik** [comment]
Hey @xyloman,

We added the configuration to the recreate-all errand. It should be available for use in the next release that's coming up shortly. 

Thanks!

**Comment by xyloman** [comment]
Thank you for the quick reply 👍
